/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IOrder } from "../IOrder";

export class IOrder__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): IOrder {
    return new Contract(address, _abi, signerOrProvider) as IOrder;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "add",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "get",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "_price",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "_offer",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "_remain",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "_type",
            type: "uint8",
          },
        ],
        internalType: "struct IOrder.OrderDetail",
        name: "order",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserOrders",
    outputs: [
      {
        internalType: "uint256[]",
        name: "ids",
        type: "uint256[]",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "_price",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "_offer",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "_remain",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "_type",
            type: "uint8",
          },
        ],
        internalType: "struct IOrder.OrderDetail[]",
        name: "orders",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_admin",
        type: "address",
      },
      {
        internalType: "address",
        name: "_orderBook",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "_price",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "_offer",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "_remain",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "_type",
            type: "uint8",
          },
        ],
        internalType: "struct IOrder.OrderDetail",
        name: "orderDetail",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "sub",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
