/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface HybridXRouterInterface extends ethers.utils.Interface {
  functions: {
    "bindFunctions(address,bytes4[])": FunctionFragment;
    "config()": FunctionFragment;
    "functionMap(bytes4)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "bindFunctions",
    values: [string, BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "functionMap",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "bindFunctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "functionMap",
    data: BytesLike
  ): Result;

  events: {};
}

export class HybridXRouter extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: HybridXRouterInterface;

  functions: {
    bindFunctions(
      clientAddress: string,
      functionIds: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "bindFunctions(address,bytes4[])"(
      clientAddress: string,
      functionIds: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    config(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "config()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    functionMap(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "functionMap(bytes4)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  bindFunctions(
    clientAddress: string,
    functionIds: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "bindFunctions(address,bytes4[])"(
    clientAddress: string,
    functionIds: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  config(overrides?: CallOverrides): Promise<string>;

  "config()"(overrides?: CallOverrides): Promise<string>;

  functionMap(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  "functionMap(bytes4)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    bindFunctions(
      clientAddress: string,
      functionIds: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "bindFunctions(address,bytes4[])"(
      clientAddress: string,
      functionIds: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    config(overrides?: CallOverrides): Promise<string>;

    "config()"(overrides?: CallOverrides): Promise<string>;

    functionMap(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    "functionMap(bytes4)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    bindFunctions(
      clientAddress: string,
      functionIds: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "bindFunctions(address,bytes4[])"(
      clientAddress: string,
      functionIds: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    config(overrides?: CallOverrides): Promise<BigNumber>;

    "config()"(overrides?: CallOverrides): Promise<BigNumber>;

    functionMap(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "functionMap(bytes4)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bindFunctions(
      clientAddress: string,
      functionIds: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "bindFunctions(address,bytes4[])"(
      clientAddress: string,
      functionIds: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    config(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "config()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    functionMap(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "functionMap(bytes4)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
