/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface OrderBookFactoryInterface extends ethers.utils.Interface {
  functions: {
    "allOrderBookLength()": FunctionFragment;
    "allOrderBookQueries(uint256)": FunctionFragment;
    "allOrderBookQueryLength()": FunctionFragment;
    "allOrderBooks(uint256)": FunctionFragment;
    "allOrderNFTLength()": FunctionFragment;
    "allOrderNFTs(uint256)": FunctionFragment;
    "config()": FunctionFragment;
    "createOrderBook(address,address)": FunctionFragment;
    "getOrderBook(address,address)": FunctionFragment;
    "getOrderBookCodeHash()": FunctionFragment;
    "getOrderBookQuery(address,address)": FunctionFragment;
    "getOrderNFT(address,address)": FunctionFragment;
    "getOrderNFTCodeHash()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "allOrderBookLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allOrderBookQueries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allOrderBookQueryLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allOrderBooks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allOrderNFTLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allOrderNFTs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createOrderBook",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderBook",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderBookCodeHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderBookQuery",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderNFT",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderNFTCodeHash",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "allOrderBookLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allOrderBookQueries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allOrderBookQueryLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allOrderBooks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allOrderNFTLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allOrderNFTs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "config", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createOrderBook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrderBook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrderBookCodeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrderBookQuery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrderNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrderNFTCodeHash",
    data: BytesLike
  ): Result;

  events: {
    "OrderBookCreated(address,address,address,address)": EventFragment;
    "OrderNFTCreated(address,address,address,address)": EventFragment;
    "OrderUtilCreated(address,address,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OrderBookCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OrderNFTCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OrderUtilCreated"): EventFragment;
}

export class OrderBookFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: OrderBookFactoryInterface;

  functions: {
    allOrderBookLength(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "allOrderBookLength()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    allOrderBookQueries(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "allOrderBookQueries(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    allOrderBookQueryLength(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "allOrderBookQueryLength()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    allOrderBooks(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "allOrderBooks(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    allOrderNFTLength(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "allOrderNFTLength()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    allOrderNFTs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "allOrderNFTs(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    config(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "config()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    createOrderBook(
      baseToken: string,
      quoteToken: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createOrderBook(address,address)"(
      baseToken: string,
      quoteToken: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getOrderBook(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getOrderBook(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getOrderBookCodeHash(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "getOrderBookCodeHash()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    getOrderBookQuery(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getOrderBookQuery(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getOrderNFT(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getOrderNFT(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getOrderNFTCodeHash(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "getOrderNFTCodeHash()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  allOrderBookLength(overrides?: CallOverrides): Promise<BigNumber>;

  "allOrderBookLength()"(overrides?: CallOverrides): Promise<BigNumber>;

  allOrderBookQueries(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "allOrderBookQueries(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  allOrderBookQueryLength(overrides?: CallOverrides): Promise<BigNumber>;

  "allOrderBookQueryLength()"(overrides?: CallOverrides): Promise<BigNumber>;

  allOrderBooks(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "allOrderBooks(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  allOrderNFTLength(overrides?: CallOverrides): Promise<BigNumber>;

  "allOrderNFTLength()"(overrides?: CallOverrides): Promise<BigNumber>;

  allOrderNFTs(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "allOrderNFTs(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  config(overrides?: CallOverrides): Promise<string>;

  "config()"(overrides?: CallOverrides): Promise<string>;

  createOrderBook(
    baseToken: string,
    quoteToken: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createOrderBook(address,address)"(
    baseToken: string,
    quoteToken: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getOrderBook(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getOrderBook(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getOrderBookCodeHash(overrides?: CallOverrides): Promise<string>;

  "getOrderBookCodeHash()"(overrides?: CallOverrides): Promise<string>;

  getOrderBookQuery(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getOrderBookQuery(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getOrderNFT(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getOrderNFT(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getOrderNFTCodeHash(overrides?: CallOverrides): Promise<string>;

  "getOrderNFTCodeHash()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    allOrderBookLength(overrides?: CallOverrides): Promise<BigNumber>;

    "allOrderBookLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    allOrderBookQueries(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "allOrderBookQueries(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    allOrderBookQueryLength(overrides?: CallOverrides): Promise<BigNumber>;

    "allOrderBookQueryLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    allOrderBooks(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "allOrderBooks(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    allOrderNFTLength(overrides?: CallOverrides): Promise<BigNumber>;

    "allOrderNFTLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    allOrderNFTs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "allOrderNFTs(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    config(overrides?: CallOverrides): Promise<string>;

    "config()"(overrides?: CallOverrides): Promise<string>;

    createOrderBook(
      baseToken: string,
      quoteToken: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "createOrderBook(address,address)"(
      baseToken: string,
      quoteToken: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getOrderBook(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getOrderBook(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getOrderBookCodeHash(overrides?: CallOverrides): Promise<string>;

    "getOrderBookCodeHash()"(overrides?: CallOverrides): Promise<string>;

    getOrderBookQuery(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getOrderBookQuery(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getOrderNFT(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getOrderNFT(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getOrderNFTCodeHash(overrides?: CallOverrides): Promise<string>;

    "getOrderNFTCodeHash()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    OrderBookCreated(
      undefined: null,
      undefined: null,
      undefined: null,
      undefined: null
    ): EventFilter;

    OrderNFTCreated(
      undefined: null,
      undefined: null,
      undefined: null,
      undefined: null
    ): EventFilter;

    OrderUtilCreated(
      undefined: null,
      undefined: null,
      undefined: null,
      undefined: null
    ): EventFilter;
  };

  estimateGas: {
    allOrderBookLength(overrides?: CallOverrides): Promise<BigNumber>;

    "allOrderBookLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    allOrderBookQueries(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allOrderBookQueries(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    allOrderBookQueryLength(overrides?: CallOverrides): Promise<BigNumber>;

    "allOrderBookQueryLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    allOrderBooks(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allOrderBooks(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    allOrderNFTLength(overrides?: CallOverrides): Promise<BigNumber>;

    "allOrderNFTLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    allOrderNFTs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allOrderNFTs(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    config(overrides?: CallOverrides): Promise<BigNumber>;

    "config()"(overrides?: CallOverrides): Promise<BigNumber>;

    createOrderBook(
      baseToken: string,
      quoteToken: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createOrderBook(address,address)"(
      baseToken: string,
      quoteToken: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getOrderBook(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getOrderBook(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOrderBookCodeHash(overrides?: CallOverrides): Promise<BigNumber>;

    "getOrderBookCodeHash()"(overrides?: CallOverrides): Promise<BigNumber>;

    getOrderBookQuery(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getOrderBookQuery(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOrderNFT(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getOrderNFT(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOrderNFTCodeHash(overrides?: CallOverrides): Promise<BigNumber>;

    "getOrderNFTCodeHash()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    allOrderBookLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allOrderBookLength()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allOrderBookQueries(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allOrderBookQueries(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allOrderBookQueryLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allOrderBookQueryLength()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allOrderBooks(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allOrderBooks(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allOrderNFTLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "allOrderNFTLength()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allOrderNFTs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allOrderNFTs(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    config(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "config()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createOrderBook(
      baseToken: string,
      quoteToken: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createOrderBook(address,address)"(
      baseToken: string,
      quoteToken: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getOrderBook(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getOrderBook(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOrderBookCodeHash(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getOrderBookCodeHash()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOrderBookQuery(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getOrderBookQuery(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOrderNFT(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getOrderNFT(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOrderNFTCodeHash(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getOrderNFTCodeHash()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
